### ISSUE TITLE
Expose only waterline instance

### ISSUE THREAD

**Issue by StarpTech** [tswayne/fast-water#3]
Hi, you shouldn't implement the logic to [load](https://github.com/tswayne/fast-water/blob/2a235b0e0d3c6dc2c5c73d521333f34778dbe836/lib/fast-water.js#L23-L31) models from the filesystem. This is really opinionated. I would just expose the waterline instance and everything else is up to the developer.

**Comment by tswayne** [comment]
The intention of this module is to be similar to how waterline is exposed in sails, which _is_ opinionated; though, exposing the waterline instance is not like exposing a mysql connection because its only use is to initialize the models (which are the useful bits).  Basically, this wouldn't be a very useful plugin if it only exposed waterline.

That being said, I'd be happy to increase the flexibility (it's already pretty flexible) should any use cases arise.

**Comment by StarpTech** [comment]
It's your plugin 👍 but in my opinion what you consider as "wouldn't be very useful" is for me the exact purpose for such plugins.

**Comment by tswayne** [comment]
No that's true, and I think that is definitely a clean approach.  What I mean is that if someone wants fastify to be decorated with waterline (so they can later register their models themselves) I don't think it's worth a module to do that:

```
module.exports =  fp(async (fastify, opts) => {
  const waterline = new Waterline();
  fastify.decorate('waterline', waterline)
})
```

This plugin actually bottles up a lot of extra logic that I think is nice for someone coming from sails that is use to (or likes) having models registered automatically.
